"""add observation type enum

Revision ID: 20260510_0001
Revises: 20260506_0001
Create Date: 2026-05-10 22:55:00.461649
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260510_0001'
down_revision: str | None = '20260506_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('HOT_CALIBRATION', 'COLD_CALIBRATION', 'TARGET_OBSERVATION', name='observationtype').create(op.get_bind())
    op.alter_column('observations', 'observation_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('HOT_CALIBRATION', 'COLD_CALIBRATION', 'TARGET_OBSERVATION', name='observationtype'),
               existing_nullable=False,
               postgresql_using='observation_type::observationtype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observations', 'observation_type',
               existing_type=sa.Enum('HOT_CALIBRATION', 'COLD_CALIBRATION', 'TARGET_OBSERVATION', name='observationtype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    sa.Enum('HOT_CALIBRATION', 'COLD_CALIBRATION', 'TARGET_OBSERVATION', name='observationtype').drop(op.get_bind())
    # ### end Alembic commands ###
