"""initial db

Revision ID: 20260601_0001
Revises: 
Create Date: 2026-06-01 19:24:40.038052
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260601_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatusenum').create(op.get_bind())
    sa.Enum('HOT_CALIBRATION', 'COLD_CALIBRATION', 'TARGET_OBSERVATION', name='observationtypeenum').create(op.get_bind())
    sa.Enum('TOPO', 'LSRK', 'BARY', 'HELIO', 'GEO', name='referenceframeenum').create(op.get_bind())
    sa.Enum('FREQ_1420_MHZ', 'FREQ_1670_MHZ', 'FREQ_22000_MHZ', name='centralfrequencyenum').create(op.get_bind())
    sa.Enum('BW_1_5_MHZ', 'BW_1_75_MHZ', 'BW_2_5_MHZ', 'BW_2_75_MHZ', 'BW_3_MHZ', 'BW_3_84_MHZ', 'BW_5_5_MHZ', 'BW_6_MHZ', 'BW_7_MHZ', 'BW_8_75_MHZ', 'BW_10_MHZ', 'BW_12_MHZ', 'BW_14_MHZ', 'BW_20_MHZ', 'BW_28_MHZ', name='bandwidthenum').create(op.get_bind())
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('observations',
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('bandwidth', postgresql.ENUM('BW_1_5_MHZ', 'BW_1_75_MHZ', 'BW_2_5_MHZ', 'BW_2_75_MHZ', 'BW_3_MHZ', 'BW_3_84_MHZ', 'BW_5_5_MHZ', 'BW_6_MHZ', 'BW_7_MHZ', 'BW_8_75_MHZ', 'BW_10_MHZ', 'BW_12_MHZ', 'BW_14_MHZ', 'BW_20_MHZ', 'BW_28_MHZ', name='bandwidthenum', create_type=False), server_default=sa.text("'BW_1_5_MHZ'"), nullable=False),
    sa.Column('center_frequency', postgresql.ENUM('FREQ_1420_MHZ', 'FREQ_1670_MHZ', 'FREQ_22000_MHZ', name='centralfrequencyenum', create_type=False), server_default=sa.text("'FREQ_1420_MHZ'"), nullable=False),
    sa.Column('velocity_frame', postgresql.ENUM('TOPO', 'LSRK', 'BARY', 'HELIO', 'GEO', name='referenceframeenum', create_type=False), server_default=sa.text("'LSRK'"), nullable=False),
    sa.Column('observation_type', postgresql.ENUM('HOT_CALIBRATION', 'COLD_CALIBRATION', 'TARGET_OBSERVATION', name='observationtypeenum', create_type=False), server_default=sa.text("'TARGET_OBSERVATION'"), nullable=False),
    sa.Column('fft_size', sa.Integer(), server_default=sa.text('1024'), nullable=False),
    sa.Column('integration_time', sa.Float(), nullable=False),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('output_filename', sa.String(length=1000), nullable=False),
    sa.Column('receive_csv', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('perform_data_analysis', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatusenum', create_type=False), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dec >= -90 AND dec <= 90', name='ck_observations_dec_range'),
    sa.CheckConstraint('integration_time > 0', name='ck_observations_integration_time_positive'),
    sa.CheckConstraint('ra >= 0 AND ra < 360', name='ck_observations_ra_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.drop_table('users')
    sa.Enum('BW_1_5_MHZ', 'BW_1_75_MHZ', 'BW_2_5_MHZ', 'BW_2_75_MHZ', 'BW_3_MHZ', 'BW_3_84_MHZ', 'BW_5_5_MHZ', 'BW_6_MHZ', 'BW_7_MHZ', 'BW_8_75_MHZ', 'BW_10_MHZ', 'BW_12_MHZ', 'BW_14_MHZ', 'BW_20_MHZ', 'BW_28_MHZ', name='bandwidthenum').drop(op.get_bind())
    sa.Enum('FREQ_1420_MHZ', 'FREQ_1670_MHZ', 'FREQ_22000_MHZ', name='centralfrequencyenum').drop(op.get_bind())
    sa.Enum('TOPO', 'LSRK', 'BARY', 'HELIO', 'GEO', name='referenceframeenum').drop(op.get_bind())
    sa.Enum('HOT_CALIBRATION', 'COLD_CALIBRATION', 'TARGET_OBSERVATION', name='observationtypeenum').drop(op.get_bind())
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
