"""add file download url columns

Revision ID: 20260601_0002
Revises: 20260601_0001
Create Date: 2026-06-01 20:24:06.625915
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260601_0002'
down_revision: str | None = '20260601_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('csv_download_url', sa.Text(), nullable=True))
    op.add_column('observations', sa.Column('analysis_results_url', sa.Text(), nullable=True))
    op.add_column('observations', sa.Column('data_download_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'data_download_url')
    op.drop_column('observations', 'analysis_results_url')
    op.drop_column('observations', 'csv_download_url')
    # ### end Alembic commands ###
