"""initial db

Revision ID: 20260506_0001
Revises: 
Create Date: 2026-05-06 20:54:44.279587
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260506_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatus').create(op.get_bind())
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('observations',
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('observation_object', sa.String(length=255), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('center_frequency', sa.Float(), nullable=False),
    sa.Column('rf_gain', sa.Float(), nullable=False),
    sa.Column('if_gain', sa.Float(), nullable=False),
    sa.Column('bb_gain', sa.Float(), nullable=False),
    sa.Column('observation_type', sa.String(length=100), nullable=False),
    sa.Column('integration_time', sa.Float(), nullable=False),
    sa.Column('output_filename', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatus', create_type=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('center_frequency > 0', name='ck_observations_center_frequency_positive'),
    sa.CheckConstraint('dec >= -90 AND dec <= 90', name='ck_observations_dec_range'),
    sa.CheckConstraint('integration_time > 0', name='ck_observations_integration_time_positive'),
    sa.CheckConstraint('ra >= 0 AND ra < 360', name='ck_observations_ra_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_observation_id'), 'observations', ['observation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_observation_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
