"""observation status from enum

Revision ID: 20260505_0002
Revises: 20260505_0001
Create Date: 2026-05-05 20:28:12.120798
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260505_0002'
down_revision: str | None = '20260505_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatus').create(op.get_bind())
    op.alter_column('observations', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatus'),
               existing_nullable=False,
               postgresql_using='status::observationstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observations', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='observationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
